### PR TITLE
Elm 0.19.1

### PR DESCRIPTION
**Pull request by brandly**
hello again!

i upgraded this app to the `0.19.1` elm compiler. the only thing that needed changing is removing the `port` declaration. the new compiler gave clear feedback:

```
This module does not declare any ports, but it says it will:

1| port module Generators.ElmDep exposing (Model, Msg(..), StateVizData(..), finishedDownloadingWith, getPathsOfElmFiles, initialModel, stateVizData, toGraphFile, update)
   ^^^^^^^^^^^
Switch this to module and you should be all set!
```

it's also [mentioned in the upgrade instructions](https://github.com/elm/compiler/blob/master/docs/upgrade-instructions/0.19.1.md#3-port-module-with-no-ports).

---

this pull request consists of two commits. the second adds a `package.json`, declaring the specific `elm` binary that's used. with this, users just `npm install` and have a local dev environment, without having to install anything globally. this is great when working on multiple projects that use different versions of `elm`. 

i modified the `Makefile` to use the locally-installed `elm`. the `package.json` also lists `make` as its `postinstall` script. upon cloning this repo, `npm install` downloads an `elm` binary _and_ `make`s the project. a full setup in a single command.

---

@erkal let me know what you think. if you just want the first commit, we can do that, but maybe you agree about the other changes 😄 

otherwise, i can also update the readme with the new development instructions! thanks.

### CODE REVIEW

**Comment by erkal** [comment]
Great. Thank you!
I was thinking about using parceljs.
What do you think about it?

**Comment by brandly** [comment]
@erkal I’ve used parcel on JS projects and enjoyed it. I haven't used it with Elm. What are you hoping to gain from it?

I’ve been using a setup like this pull request on Elm projects lately. The elm compiler on its own is very fast. Here’s a project that has a script that produces a minified bundle and pushes it to gh pages. https://github.com/brandly/elm-dr-mario/blob/master/package.json

**Comment by erkal** [comment]
This looks very nice.
Having something like this, we would also to get rid of makefile and the deploy script.

**Comment by erkal** [comment]
on the other hand, if we use parcel, it watches the files and rebuilds on save

**Comment by brandly** [comment]
^ the setup i linked to has been nice. the `elm` binary is _very_ fast, like `0.05s`, but running `npm run build` puts it up to like `0.60s`. the extra time is spent initializing a JS runtime, i think. i was considering moving to a `Makefile` for this reason haha

i don't have any experience using parcel with Elm. having it watch files and do incremental builds on JS projects is nice, since JS builds tend to be very slow by comparison. 

[looking at this](https://parceljs.org/elm.html), it appears you point it at an `html` file, which is kinda nice. however, that html references a JS file, so maybe the builds are slower and more involved due to the surrounding JS. i don't really know.

it's your decision though!

**Comment by erkal** [comment]
Ok, after all the conversation, I've found the way in your pull request the best.
I didn't know that npm adds so much time.

**Comment by erkal** [comment]
If you update the README, I'll merge it to master.

**Comment by brandly** [comment]
thanks for discussing everything!

**Comment by erkal** [comment]
thank you for taking the effort to explain.
it saved plenty of time for me.
❤️

**Pull request merged**
