### PR TITLE
give better feedback on common GitHub http errors

### PR DESCRIPTION
**Pull request by brandly**
partially addresses #11

i don't think that issue is _fixed_, but i added some error messages that encourage using an access token. this should help prevent people from getting stuck.

### CODE REVIEW

**Comment by erkal** [comment]
this created a conflict because I've merged #18 before.
would you fix it or I can look into it later

**Comment by brandly** [comment]
Yeah I realized that second commit would be an issue. I’ll take care of it soon!

**Comment by brandly** [comment]
@erkal should be good now!

**Comment by erkal** [comment]
👍 thank you very much

**Pull request merged**
